package Proyecto;

import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Principal extends javax.swing.JFrame {

    ProyectoDepreciacion proy = new ProyectoDepreciacion();

    public Principal() {
        initComponents();
    }
Mantenimiento frame = new Mantenimiento();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TipoActivo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValorActivo = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        txtValorRescate = new javax.swing.JTextField();
        txtResponsable = new javax.swing.JTextField();
        txtVidaUtil = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnCalculo = new javax.swing.JButton();
        rbSumaDigitos = new javax.swing.JRadioButton();
        RbLineaRecta = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        Btnagregar = new javax.swing.JButton();
        Btnlimpiar = new javax.swing.JButton();
        CBelegirActivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Btnlimpiartabla = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LbActivoselect = new javax.swing.JLabel();
        btnBuscarAct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("     Sistema de Depreciación de Activos");
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);

        TipoActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corriente", "No Corriente" }));
        TipoActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActivoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Información de Activo");

        jLabel3.setText("Código ");
        jLabel3.setToolTipText("");

        jLabel4.setText("Nombre");

        jLabel5.setText("Tipo de activo");

        jLabel6.setText("Valor de Activo");

        jLabel7.setText("Valor de Rescate");

        jLabel8.setText("Responsable");

        jLabel9.setText("Vida Util");

        txtValorActivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorActivoKeyTyped(evt);
            }
        });

        txtcodigo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtcodigo.setName("txtCodigo"); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });

        txtValorRescate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorRescateKeyTyped(evt);
            }
        });

        txtResponsable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResponsableKeyTyped(evt);
            }
        });

        txtVidaUtil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaUtilActionPerformed(evt);
            }
        });
        txtVidaUtil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVidaUtilKeyTyped(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        btnCalculo.setBackground(new java.awt.Color(68, 90, 79));
        btnCalculo.setText("Calcular Depreciación");
        btnCalculo.setEnabled(false);
        btnCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(rbSumaDigitos);
        rbSumaDigitos.setSelected(true);
        rbSumaDigitos.setText("Suma de Digitos");
        rbSumaDigitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSumaDigitosActionPerformed(evt);
            }
        });

        buttonGroupTipo.add(RbLineaRecta);
        RbLineaRecta.setText("Linea recta");

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Año", "Código", "Tipo Activo", "Valor Activo", "Valor Rescate", "Tipo Depreciación", "Dep. Anual", "Dep. Acumulada", "Valor Periodo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        Btnagregar.setBackground(new java.awt.Color(68, 90, 79));
        Btnagregar.setText("Agregar");
        Btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnagregarActionPerformed(evt);
            }
        });

        Btnlimpiar.setBackground(new java.awt.Color(153, 62, 60));
        Btnlimpiar.setLabel("Limpiar");
        Btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlimpiarActionPerformed(evt);
            }
        });

        CBelegirActivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBelegirActivoItemStateChanged(evt);
            }
        });
        CBelegirActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBelegirActivoActionPerformed(evt);
            }
        });

        jLabel10.setText("Selección de Activo");

        Btnlimpiartabla.setBackground(new java.awt.Color(153, 62, 60));
        Btnlimpiartabla.setText("Limpiar Tabla");
        Btnlimpiartabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlimpiartablaActionPerformed(evt);
            }
        });

        jLabel11.setText("Seleccione el tipo de depreciación");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Calculo de depreciación");

        LbActivoselect.setText("Activo seleccionado");

        btnBuscarAct.setBackground(new java.awt.Color(68, 90, 79));
        btnBuscarAct.setText("Buscar Activo ");
        btnBuscarAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcodigo)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TipoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtValorActivo))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Btnagregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Btnlimpiar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVidaUtil, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(txtValorRescate)
                                    .addComponent(txtResponsable))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbSumaDigitos)
                                .addGap(18, 18, 18)
                                .addComponent(RbLineaRecta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(CBelegirActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LbActivoselect)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(345, 345, 345))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscarAct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Btnlimpiartabla)))
                                .addGap(28, 28, 28))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CBelegirActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbActivoselect))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculo)
                            .addComponent(jLabel11)
                            .addComponent(rbSumaDigitos)
                            .addComponent(RbLineaRecta))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TipoActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValorActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtValorRescate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtVidaUtil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnagregar)
                            .addComponent(Btnlimpiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnlimpiartabla)
                            .addComponent(btnBuscarAct))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSumaDigitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSumaDigitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSumaDigitosActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoActionPerformed

        proy.Buscar(String.valueOf(CBelegirActivo.getSelectedItem()));
        float deprelinearecta = 0;
        float depresuma[] = new float[Integer.parseInt(proy.vidaUtil)];
         DecimalFormat df = new DecimalFormat("#");
        df.setMaximumFractionDigits(4);

        if (rbSumaDigitos.isSelected()) {

            depresuma = proy.SumaDigitos(Integer.parseInt(proy.valorActivo), Integer.parseInt(proy.valorRescate), Integer.parseInt(proy.vidaUtil));
            DefaultTableModel model=(DefaultTableModel)jTabla.getModel();
            float depacum=0;
            for(int i=0; i<Integer.parseInt(proy.vidaUtil);i++){
            
                int year= Integer.parseInt(proy.vidaUtil)-i;
                depacum=depresuma[i]+depacum;
                float vfinal= Integer.parseInt(proy.valorActivo)-depacum;
             
            Object[] row={Integer.toString(year),proy.codigo,proy.tipoActivo,proy.valorActivo,proy.valorRescate,"Suma Digitos",df.format(depresuma[i]),df.format(depacum),df.format(vfinal)};
            model.addRow(row); 
            }
        }
        if (RbLineaRecta.isSelected()) {
            
            DefaultTableModel model=(DefaultTableModel)jTabla.getModel();
            deprelinearecta = proy.LineaRecta(Integer.parseInt(proy.valorActivo), Integer.parseInt(proy.valorRescate), Integer.parseInt(proy.vidaUtil));
            String datosdepre="";
            
            for(int i=0; i<Integer.parseInt(proy.vidaUtil);i++){
            int year= i+1;
            float depacum=deprelinearecta*(i+1);
            float vfinal= Integer.parseInt(proy.valorActivo)-depacum;
           
            datosdepre= datosdepre+year+";"+df.format(deprelinearecta)+";"+df.format(depacum)+";"+df.format(vfinal)+";";
          
            Object[] row={Integer.toString(year),proy.codigo,proy.tipoActivo,proy.valorActivo,proy.valorRescate,"Línea Recta",df.format(deprelinearecta),df.format(depacum),df.format(vfinal)};
            model.addRow(row); 
            
            }
            
            if (proy.BuscarDepreciacion(proy.codigo)==false){
            proy.DepreciacionArrayList.add(proy.codigo+";"+datosdepre);
            }else{
            
                proy.BuscarEliminarDepreciacion(proy.codigo);
                proy.DepreciacionArrayList.add(proy.codigo+";"+datosdepre);
            }
        }

    }//GEN-LAST:event_btnCalculoActionPerformed

    private void TipoActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActivoActionPerformed

    private void BtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnagregarActionPerformed
        String cod;

        boolean nom = proy.validartexto(txtNombre.getText());
        boolean co = proy.validartexto(txtcodigo.getText());
        boolean vact = proy.validartexto(txtValorActivo.getText());
        boolean valResc = proy.validartexto(txtValorRescate.getText());
        boolean resp = proy.validartexto(txtResponsable.getText());
        boolean vidaUtil = proy.validartexto(txtVidaUtil.getText());
        
      
        if ((nom == false) || (co == false) || (vact == false) || (valResc == false) || (resp == false) || (vidaUtil == false)) {
            JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
            
        } else if (Integer.parseInt(txtVidaUtil.getText())>10){
        JOptionPane.showMessageDialog(null, "La vida útil del activo debe ser menor a 10 años");
        
        }else if (Integer.parseInt(txtValorRescate.getText()) < Integer.parseInt(txtValorActivo.getText())) {
            
        DefaultComboBoxModel model =(DefaultComboBoxModel)CBelegirActivo.getModel();// Traer el modelo del combobox
        
        if(model.getIndexOf(txtcodigo.getText())!=-1){ //Valida si el código ya existe en el combobox
        JOptionPane.showMessageDialog(null, "Ya existe un activo con el código:"+txtcodigo.getText());
        } 
        else{ 
            cod = proy.CapturarDatos(txtNombre.getText(), txtcodigo.getText(), TipoActivo.getSelectedItem().toString(), txtValorActivo.getText(), txtValorRescate.getText(), txtResponsable.getText(), txtVidaUtil.getText());
            CBelegirActivo.addItem(cod);

            boolean act = proy.validartexto(CBelegirActivo.getSelectedItem().toString());
            if (act == true) {
                btnCalculo.setEnabled(true);
            }
        }
        }else{
            JOptionPane.showMessageDialog(null, "El valor del activo debe ser menor a valor de rescate.");
        }
        
    }//GEN-LAST:event_BtnagregarActionPerformed

    private void BtnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlimpiarActionPerformed
        txtcodigo.setText(null);
        txtNombre.setText(null);
        txtValorActivo.setText(null);
        txtValorRescate.setText(null);
        txtResponsable.setText(null);
        txtVidaUtil.setText(null);
    }//GEN-LAST:event_BtnlimpiarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isLetterOrDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char enter = evt.getKeyChar();
        if ((Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtValorActivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorActivoKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorActivoKeyTyped

    private void txtValorRescateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRescateKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorRescateKeyTyped

    private void txtResponsableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsableKeyTyped
        char enter = evt.getKeyChar();
        if ((Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtResponsableKeyTyped

    private void txtVidaUtilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVidaUtilKeyTyped
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtVidaUtilKeyTyped

    private void BtnlimpiartablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlimpiartablaActionPerformed

       DefaultTableModel model=(DefaultTableModel)jTabla.getModel();
        model.setRowCount(0);
      
    }//GEN-LAST:event_BtnlimpiartablaActionPerformed

    private void btnBuscarActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActActionPerformed
        frame.setVisible(true);
          
    }//GEN-LAST:event_btnBuscarActActionPerformed

    private void CBelegirActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBelegirActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBelegirActivoActionPerformed

    private void CBelegirActivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBelegirActivoItemStateChanged
        
        proy.Buscar(String.valueOf(CBelegirActivo.getSelectedItem()));
        
        LbActivoselect.setText("Activo: " +proy.nombre);

    }//GEN-LAST:event_CBelegirActivoItemStateChanged

    private void txtVidaUtilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaUtilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidaUtilActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnagregar;
    private javax.swing.JButton Btnlimpiar;
    private javax.swing.JButton Btnlimpiartabla;
    private javax.swing.JComboBox<String> CBelegirActivo;
    private javax.swing.JLabel LbActivoselect;
    private javax.swing.JRadioButton RbLineaRecta;
    private javax.swing.JComboBox<String> TipoActivo;
    private javax.swing.JButton btnBuscarAct;
    private javax.swing.JButton btnCalculo;
    private javax.swing.ButtonGroup buttonGroupTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JRadioButton rbSumaDigitos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtValorActivo;
    private javax.swing.JTextField txtValorRescate;
    private javax.swing.JTextField txtVidaUtil;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables
}
